### PR TITLE
[GBI-744] Penalize missbehaving LP

### PR DESCRIPTION
**Pull request by manfioLP**

### CODE REVIEW

**Comment by ricardo-iov** [comment]
Hello @manfioLP looks like your changes are not passing the unit test. Please, take a look.

**Review by ricardo-iov — COMMENTED** [review]
Hello @manfioLP looks like your changes are not passing the unit test. Please, take a look.

**Comment by manfioLP** [comment]
hey @ricardo-iov thanks for checking, I belive they're fixed now!

**Comment by ricardo-iov** [comment]
> hey @ricardo-iov thanks for checking, I belive they're fixed now!

Test are working good now. Thanks :)

**Review by MaximStanciu8 — APPROVED** [review]

**Review by MaximStanciu8 — APPROVED** [review]

**Pull request merged**
